### ISSUE TITLE
[FEATURE] 상품 정보 수정하기

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/pppick-back#15]
## 📄Description
회원은 상품명, 상세설명, 가격정보를 수정 할 수 있다

## ✅ Todo
- [ ] 상품 수정 테스트 만들기
- [ ] 상품 서비스에서 상품 수정 구현하기
- [ ] 상품 컨트롤러를 만들어 상품 수정 api 제작하기
- [ ] Swagger ui를 통해 상품 수정 api 테스트하기

## 🔖ETC
기타사항
