### ISSUE TITLE
[FEATURE] 상품 이미지 파일 업로드 기능 구현

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/pppick-back#17]
## 📄Description
회원은 상품을 등록 시 이미지 파일 업로드를 할 수 있다

## ✅ Todo
- [ ] 상품 이미지 클래스 만들기
- [ ] 상품 이미지 업로드 테스트 만들기
- [ ] 상품 이미지 레포지토리 만들기
- [ ] 상품 서비스에서 이미지 업로드 구현하기
- [ ] 상품 컨트롤러를 만들어 상품 이미지 업로드 api 제작하기
- [ ] Swagger ui를 통해 상품 이미지 업로드 api 테스트하기

## 🔖ETC
기타사항
