### ISSUE TITLE
[FEATURE] 상품 이미지 삭제

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/pppick-back#20]
## 📄Description
회원은 상품 이미지를 삭제할 수 있다

## ✅ Todo
- [ ] 상품 이미지 삭제 테스트 만들기
- [ ] 상품 서비스에서 상품 이미지 삭제 기능 구현하기
- [ ] 상품 컨트롤러를 만들어 상품 이미지 삭제 api 제작하기
- [ ] Swagger ui를 통해 상품 이미지 삭제 api 테스트하기

## 🔖ETC
기타사항
