### ISSUE TITLE
[FEATURE] 상품 정보 등록하기

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/pppick-back#4]
## 📄Description
회원은 상품명, 상세설명, 가격을 입력하여 상품 정보를 저장할 수 있다

## ✅ Todo
- [x] 상품 등록 테스트 만들기
- [x] 상품 레포지토리 구현하기
- [x] 상품 서비스에서 상품 등록 구현하기
- [x] 상품 컨트롤러를 만들어 상품 등록 api 제작하기
- [x] Swagger ui를 통해 상품 등록 api 테스트하기

## 🔖ETC
기타사항
