### ISSUE TITLE
API 명세서 작성 및 역할 분담

### ISSUE THREAD

**Issue by KIM-DO-HEE** [KIM-DO-HEE/pppick-back#9]
## Description
POST MAN을 이용하여 API 명세서 작성

## Todo

- [x] 사용자 관리 api 명세서 작성
- [x] 작업물 관리 api 명세서 작성 
- [x] 게시글 관리 api 명세서 작성 
- [x] 상품 및 결제 관리 api 명세서 작성
- [x] 좋아요 / 태그 관리 api 명세서 작성
- [x] 관리자 관리 api 명세서 작성
- [x] api 개발 역할 분담

## ETC
상품과 결제 관리 담당하게 됨
